redis: &redis
  adapter: redis
  url: redis://localhost:6379/1

development:
  adapter: redis
  url: redis://localhost:6379/1

test: *redis

production:
  url: <%= ENV.fetch("REDIS_URL") %>
  channel_prefix: project1102_production
  host: <%= ENV.fetch("REDIS_HOST") %>
  password: <%= ENV.fetch('REDIS_PASSWORD') %>
  port: 9379
