redis: &redis
  adapter: redis
  url: redis://localhost:6379/1

development:
  adapter: redis
  url: redis://localhost:6379/1

test: *redis

production:
  url: <%= ENV("REDIS_URL") %>
  channel_prefix: project1102_production
  host: <%= ENV("REDIS_HOST") %>
  password: <%= ENV('REDIS_PASSWORD') %>
  port: 9379